[package]
name = "seer-assistant"
version.workspace = true
edition.workspace = true

[dependencies]
lariv-rs = { workspace = true }
seer-intel = { workspace = true }
frunk = { workspace = true }
frunk_core = { workspace = true }
sea-orm = { workspace = true }
async-trait = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
